<?php

function theme_options_array() {

	$options=array(

	// MAIN PAGE OPTIONS
	"main" => array( "title" => esc_html__( "Theme Settings" , "essu" ),

	// GENERAL SECTION
	esc_html__( "General" , "essu" ) => array(
	array( "options" => array( "title" => esc_html__( "Logo" , "essu" ), "class" => "section-upload" ),
		"custom_logo" => array( "name" => esc_html__('Logo',"essu" ),
			"type" => "image",
			"desc" => esc_html__( "Supported formats: JPG, PNG" , "essu" ),
			"std" => "", 
		),
	),
	array( "options" => array( "title" => esc_html__( "Retina Logo" , "essu" ), "class" => "section-upload" ),
		"custom_retina_logo" => array( "name" => esc_html__('Retina Logo',"essu" ),
			"type" => "image",
			"desc" => esc_html__( "Supported formats: JPG, PNG" , "essu" ),
			"std" => "", 
		),
	),
	array( "options" => array( "title" => esc_html__( "Page Preloading Effect" , "essu" ) ),
		"global_preloading" => array( "name" => esc_html__( 'Enable smart preloading effect.',"essu" ),
			"type" => "onoff",
			"desc" => esc_html__( "Global setting. Enable smart preloading effect." , "essu" ),
			"std" => "false",
		),
	),
	array( "options" => array( "title" => esc_html__( "Content Protection" , "essu" ) ),
		"content_protection" => array( "name" => esc_html__('Enable Content Protection',"essu" ),
			"type" => "onoff",
			"desc" => esc_html__( "Enable/disable right click protection" , "essu" ),
			"std" => "false",
		),
		"protection_message" => array( "name" => esc_html__(' ',"essu" ),
			"type" => "textarea",
			"desc" => esc_html__( "This message will display when the user clicks the right button and protection is turned on" , "essu" ),
			"std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Footer copyrights" , "essu" ) ),
		"copyrights" => array( "name" => esc_html__('Paste your copyrights text here',"essu" ),
			"type" => "textarea",
			"desc" => esc_html__( "Paste your copyrights text here. You may use these HTML tags and attributes" , "essu" ),
			"std" => "&copy; Essu theme by <a  target='_blank' href='http://themeforest.net/user/kotofey?ref=kotofey'>kotofey</a>. All Rights Reserved.",
		),
	),
	),

	// APPEARANCE
	esc_html__( "Appearance" , "essu" ) => array(
	array( "options" => array( "title" => esc_html__( "Menu" , "essu" ) ),
		"menu_style" => array( "name" => esc_html__( "Menu style" , "essu" ),
			"type" => "select",
			"options"  =>  array(
						"classic" => "Classic",
						"minimal" => "Minimal",
						"side" => "Side"
			),
			"desc" => esc_html__( "Select menu style" , "essu" ),
			"std" => "classic",
		),
	),
	array( "options" => array( "title" => esc_html__( "Skin color" , "essu" ) ),
		"skin" => array( "name" => esc_html__('Select a color to be used as accents color.',"essu" ),
			"type" => "color",
			"desc" => esc_html__( "Select a color to be used as accents color." , "essu" ),
			"std" => ""
		),
	),
	array( "options" => array( "title" => esc_html__( "Project's overlay" , "essu" ) ),
		"dominant_color" => array( "name" => esc_html__( 'Enable automatic overlay color',"essu" ),
			"type" => "onoff",
			"desc" => esc_html__( 'By enabling this option the overlay color, used for projects on portfolio page, will be set automatically. The dominant color from image will be set as main.' , "essu" ),
			"std" => 'true'
		),
		"dominant_color_custom" => array( "name" => esc_html__( 'Set overlay color',"essu" ),
			"type" => "color",
			"desc" => esc_html__( "Set overlay color" , "essu" ),
			"std" => ""
		),
		"dominant_color_text" => array( "name" => esc_html__( 'Set overlay text color',"essu" ),
			"type" => "color",
			"desc" => esc_html__( "Set overlay text color" , "essu" ),
			"std" => ""
		),
	),
	array( "options" => array( "title" => esc_html__( "Custom CSS" , "essu" ) ),
		"custom_css" => array( "name" => esc_html__('Add some CSS to your theme by adding it to this area.',"essu" ),
			"type" => "textarea",
			"desc" => esc_html__( "Add some CSS to your theme by adding it to this area." , "essu" ),
			"std" => "",
		),
	),
	),  
	 
	// SOCIAL SECTION
	esc_html__( "Social" , "essu" ) => array(
	array( "options" => array( "title" => esc_html__( "Facebook" , "essu" ) ),
		"facebook" => array( "name" => esc_html__('Enter the  link to your facebook account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your Facebook account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Twitter" , "essu" ) ),
		"twitter" => array( "name" => esc_html__('Enter the  link to your twitter account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your Twitter account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Google+" , "essu" ) ),
		"google" => array( "name" => esc_html__('Enter the  link to your Google plus account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your google plus account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Pinterest" , "essu" ) ),
		"pinterest" => array( "name" => esc_html__('Enter the  link to your Pinterest account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your Pinterest account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Instagram" , "essu" ) ),
		"instagram" => array( "name" => esc_html__('Enter the  link to your Instagram account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your Instagram account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Soundcloud" , "essu" ) ),
		"soundcloud" => array( "name" => esc_html__('Enter the  link to your Soundcloud account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your Soundcloud plus account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "500px" , "essu" ) ),
		"500px" => array( "name" => esc_html__('Enter the  link to your 500px account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your 500px plus account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Youtube" , "essu" ) ),
		"youtube" => array( "name" => esc_html__('Enter the  link to your Youtube account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your youtube account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Vimeo" , "essu" ) ),
		"vimeo" => array( "name" => esc_html__('Enter the  link to your Vimeo account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your vimeo account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Flickr" , "essu" ) ),
		"flickr" => array( "name" => esc_html__('Enter the  link to your flickr account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your Flickr account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Skype" , "essu" ) ),
		"skype" => array( "name" => esc_html__('Enter your Skype name or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter your skype name or leave this field blank. I.e: skype:skypename" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Linkedin" , "essu" ) ),
		"linkedin" => array( "name" => esc_html__('Enter the  link to your Linkedin account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your linkedin account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	array( "options" => array( "title" => esc_html__( "Tumblr" , "essu" ) ),
		"tumblr" => array( "name" => esc_html__('Enter the  link to your Tumblr account or leave this field blank',"essu" ),
		  "type" => "text",
		  "desc" => esc_html__( "Enter the  link to your Tumblr account or leave this field blank" , "essu" ),
		  "std" => "",
		),
	),
	),

	), // END MAIN PAGE

	);

  return $options;
}